'use client';
import React, { useState, useEffect } from 'react';
import { AI_MODELS } from '@/types';
import { store } from '@/lib/store';

export default function Settings() {
  const [keys, setKeys] = useState<Record<string, string>>({});
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    setKeys(store.getApiKeys());
  }, []);

  const providers = [
    { id: 'openai', name: 'OpenAI', icon: '🟢', placeholder: 'sk-...' },
    { id: 'anthropic', name: 'Anthropic', icon: '🟠', placeholder: 'sk-ant-...' },
    { id: 'google', name: 'Google Gemini', icon: '🔵', placeholder: 'AIza...' },
    { id: 'mistral', name: 'Mistral', icon: '🟣', placeholder: 'api-key...' },
    { id: 'nvidia', name: 'NVIDIA API', icon: '🟩', placeholder: 'nvapi-...' },
    { id: 'ollama', name: 'Ollama Cloud', icon: '🦙', placeholder: 'ollama-...' },
  ];

  const [ollamaModels, setOllamaModels] = useState<any[]>([]);
  const [ollamaError, setOllamaError] = useState('');

  useEffect(() => {
    fetch('/api/ollama')
      .then(res => res.json())
      .then(data => {
        if (data.error) throw new Error(data.error);
        if (data.models) setOllamaModels(data.models);
      })
      .catch(err => {
        setOllamaError('Could not connect to Ollama. Please run `ollama serve` or download it.');
      });
  }, []);

  const handleSave = () => {
    Object.entries(keys).forEach(([provider, key]) => {
      if (key) store.setApiKey(provider, key);
    });
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  const generateRulesContent = () => {
    const prompts = store.getPrompts();
    const topPrompts = prompts.slice(0, 10);

    let rules = `# Auto-generated by PromptStudio — DO NOT EDIT MANUALLY\n`;
    rules += `## Your Role\nYou are a senior full-stack engineer working on a production codebase.\n`;
    rules += `Always apply these principles from your top-rated prompts:\n\n`;

    const byCategory = new Map<string, typeof topPrompts>();
    topPrompts.forEach(p => {
      const cat = p.category;
      if (!byCategory.has(cat)) byCategory.set(cat, []);
      byCategory.get(cat)!.push(p);
    });

    byCategory.forEach((prompts, category) => {
      rules += `## ${category.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}\n`;
      prompts.forEach(p => {
        const firstLine = p.template.split('\n')[0].slice(0, 100);
        rules += `- ${firstLine}\n`;
      });
      rules += `\n`;
    });

    rules += `## Red Flags — Never Do These\n`;
    rules += `- Never use any as a type in TypeScript\n`;
    rules += `- Never commit secrets or API keys\n`;
    rules += `- Never ignore error handling\n`;
    rules += `- Never write code without considering edge cases\n`;
    rules += `- Never skip input validation\n`;
    return rules;
  };

  const copyRules = (filename: string) => {
    navigator.clipboard.writeText(generateRulesContent());
    alert(`Rules copied! Paste into ${filename} file/settings.`);
  };

  const downloadRules = (filename: string) => {
    const blob = new Blob([generateRulesContent()], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="animate-fade-in">
      <div className="page-header">
        <h1>⚙️ Settings</h1>
        <p>Configure API keys and integrations — all keys stored locally in your browser only</p>
      </div>

      <div className="page-body" style={{ maxWidth: '640px' }}>
        {/* API Keys */}
        <div className="card" style={{ marginBottom: 'var(--space-lg)', cursor: 'default' }}>
          <h3 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: 'var(--space-md)' }}>
            🔑 API Keys
          </h3>
          <p style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', marginBottom: 'var(--space-md)' }}>
            Keys are stored in localStorage only. Never sent to any server.
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}>
            {providers.map(p => (
              <div key={p.id} className="input-group">
                <label>{p.icon} {p.name}</label>
                <input
                  className="input"
                  type="password"
                  value={keys[p.id] || ''}
                  onChange={e => setKeys(prev => ({ ...prev, [p.id]: e.target.value }))}
                  placeholder={p.placeholder}
                />
              </div>
            ))}
          </div>

          <button className="btn btn-primary mt-md" onClick={handleSave}>
            {saved ? '✅ Saved!' : '💾 Save Keys'}
          </button>
        </div>

        {/* Available Models */}
        <div className="card" style={{ marginBottom: 'var(--space-lg)', cursor: 'default' }}>
          <h3 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: 'var(--space-md)' }}>
            🤖 Available Models
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
            {AI_MODELS.map(m => (
              <div key={m.id} style={{
                display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                padding: '10px 14px', background: 'var(--bg-tertiary)',
                borderRadius: 'var(--radius-md)', fontSize: '0.82rem',
                flexWrap: 'wrap', gap: '4px',
              }}>
                <div style={{ minWidth: 0 }}>
                  <span style={{ fontWeight: 600 }}>{m.name}</span>
                  <span style={{ color: 'var(--text-tertiary)', marginLeft: '8px', fontSize: '0.75rem' }}>{m.provider}</span>
                </div>
                <div style={{ color: 'var(--text-tertiary)', flexShrink: 0, fontSize: '0.78rem' }}>
                  {keys[m.provider] ? (
                    <span style={{ color: '#ffb300' }}>● Connected</span>
                  ) : (
                    <span style={{ color: 'var(--text-tertiary)' }}>○ No key</span>
                  )}
                </div>
              </div>
            ))}
          </div>
          
          <h4 style={{ fontSize: '0.85rem', fontWeight: 600, marginTop: 'var(--space-md)', marginBottom: '8px' }}>
            🦙 Local Models (Ollama)
          </h4>
          {ollamaError ? (
            <div style={{ padding: '10px 14px', background: 'rgba(239, 68, 68, 0.1)', color: '#ef4444', borderRadius: 'var(--radius-md)', fontSize: '0.82rem' }}>
              {ollamaError}
            </div>
          ) : ollamaModels.length > 0 ? (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
              {ollamaModels.map(m => (
                <div key={m.name} style={{
                  display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                  padding: '10px 14px', background: 'var(--bg-tertiary)',
                  borderRadius: 'var(--radius-md)', fontSize: '0.82rem',
                }}>
                  <div>
                    <span style={{ fontWeight: 600 }}>{m.name}</span>
                    <span style={{ color: 'var(--text-tertiary)', marginLeft: '8px' }}>ollama</span>
                  </div>
                  <div style={{ color: '#ffb300' }}>● Connected</div>
                </div>
              ))}
            </div>
          ) : (
            <div style={{ fontSize: '0.82rem', color: 'var(--text-tertiary)' }}>Loading Ollama models...</div>
          )}
        </div>

        {/* Integrations */}
        <div className="card" style={{ cursor: 'default' }}>
          <h3 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: 'var(--space-md)' }}>
            🔌 Integrations
          </h3>
          <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: 'var(--space-lg)' }}>
            Export your top-rated prompts as a knowledge base file for your AI assistants.
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}>
            
            {/* Antigravity AI */}
            <div style={{
              padding: '16px', background: 'var(--bg-tertiary)',
              borderRadius: 'var(--radius-md)', border: '1px solid var(--border-subtle)',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px' }}>
                <span style={{ fontSize: '1.2rem' }}>🛸</span>
                <div style={{ fontWeight: 600, fontSize: '0.95rem' }}>Antigravity AI</div>
              </div>
              <div style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', marginBottom: '16px' }}>
                Seamless integration with your Google DeepMind agentic platform.
              </div>
              
              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', background: 'var(--bg-secondary)', padding: '12px', borderRadius: '6px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '8px' }}>
                  <span style={{ fontSize: '0.85rem', fontWeight: 500 }}>1. Download rules file</span>
                  <button className="btn btn-primary btn-sm" onClick={() => downloadRules('.rules.md')}>
                    ⬇️ Download .rules.md
                  </button>
                </div>
                
                <hr style={{ border: 'none', borderTop: '1px solid var(--border-subtle)' }} />
                
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', flexWrap: 'wrap', gap: '8px' }}>
                  <div style={{ flex: 1 }}>
                    <span style={{ fontSize: '0.85rem', fontWeight: 500 }}>2. Initial Context Prompt</span>
                    <div style={{ 
                      background: 'rgba(0,0,0,0.2)', padding: '8px', borderRadius: '4px', 
                      fontFamily: 'monospace', fontSize: '0.75rem', color: 'var(--text-secondary)',
                      marginTop: '4px', border: '1px solid var(--border-subtle)',
                      wordWrap: 'break-word', wordBreak: 'break-all', whiteSpace: 'pre-wrap'
                    }}>
                      Please read the .rules.md file in this directory first and use it as your base context and coding guidelines before starting work.
                    </div>
                  </div>
                  <button 
                    className="btn btn-secondary btn-sm" 
                    style={{ marginLeft: '12px', marginTop: '16px' }}
                    onClick={() => {
                      navigator.clipboard.writeText("Please read the .rules.md file in this directory first and use it as your base context and coding guidelines before starting work.");
                      alert("Prompt copied to clipboard!");
                    }}
                  >
                    📋 Copy
                  </button>
                </div>
              </div>
            </div>

            {/* VS Code (Copilot / Extensions) */}
            <div style={{
              padding: '16px', background: 'var(--bg-tertiary)',
              borderRadius: 'var(--radius-md)', border: '1px solid var(--border-subtle)',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px' }}>
                <span style={{ fontSize: '1.2rem' }}>💻</span>
                <div style={{ fontWeight: 600, fontSize: '0.95rem' }}>VS Code (GitHub Copilot / RooCode)</div>
              </div>
              <div style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', marginBottom: '16px' }}>
                Generate custom instructions for VS Code extensions to follow automatically.
              </div>
              
              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', background: 'var(--bg-secondary)', padding: '12px', borderRadius: '6px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '8px' }}>
                  <span style={{ fontSize: '0.85rem', fontWeight: 500 }}>Global AI Instructions</span>
                  <button className="btn btn-secondary btn-sm" onClick={() => copyRules('VS Code Settings')}>
                    📋 Copy Rules
                  </button>
                </div>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-tertiary)' }}>
                  Paste into your VS Code User Settings under <code>github.copilot.chat.codeGeneration.instructions</code> or extension settings.
                </div>
              </div>
            </div>

            {/* Cursor IDE */}
            <div style={{
              padding: '16px', background: 'var(--bg-tertiary)',
              borderRadius: 'var(--radius-md)', border: '1px solid var(--border-subtle)',
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '8px' }}>
                <div>
                  <div style={{ fontWeight: 600, fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    🖱️ Cursor IDE
                  </div>
                  <div style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', marginTop: '4px' }}>
                    Copy rules to clipboard and paste into your project's .cursorrules file.
                  </div>
                </div>
                <button className="btn btn-secondary btn-sm" onClick={() => copyRules('.cursorrules')}>
                  📋 Copy
                </button>
              </div>
            </div>

            {/* Windsurf IDE */}
            <div style={{
              padding: '16px', background: 'var(--bg-tertiary)',
              borderRadius: 'var(--radius-md)', border: '1px solid var(--border-subtle)',
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '8px' }}>
                <div>
                  <div style={{ fontWeight: 600, fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    🏄‍♂️ Windsurf IDE
                  </div>
                  <div style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', marginTop: '4px' }}>
                    Copy rules to clipboard and paste into your project's .windsurfrules file.
                  </div>
                </div>
                <button className="btn btn-secondary btn-sm" onClick={() => copyRules('.windsurfrules')}>
                  📋 Copy
                </button>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
}
